//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_Eventos()
        {
            this.RegistrosEvento = new HashSet<RegistrosEvento>();
        }
    
        public int Evento_Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> EdicionFecha { get; set; }
        public Nullable<int> EdicionUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrosEvento> RegistrosEvento { get; set; }
    }
}
