//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.RegistrosEvento = new HashSet<RegistrosEvento>();
            this.Tokens = new HashSet<Tokens>();
        }
    
        public int Paciente_Id { get; set; }
        public int Usuario_Id { get; set; }
        public Nullable<int> Terapeuta_Id { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> EdicionFecha { get; set; }
        public Nullable<int> EdicionUsuario { get; set; }
    
        public virtual Terapeutas Terapeutas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrosEvento> RegistrosEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tokens> Tokens { get; set; }
    }
}
