//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosEvento
    {
        public int RegistroEvento_Id { get; set; }
        public int Evento_Id { get; set; }
        public int Paciente_Id { get; set; }
        public Nullable<System.DateTime> CreacionFecha { get; set; }
        public string Valor { get; set; }
    
        public virtual CT_Eventos CT_Eventos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
