//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Modulos
    {
        public int Rol_Modulo_Id { get; set; }
        public int Rol_Id { get; set; }
        public int Modulo_Id { get; set; }
        public Nullable<System.DateTime> CreacionFecha { get; set; }
        public Nullable<int> CreacionUsuario { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
